image: docker:20
variables:
  DOCKER_HOST: tcp://docker:2375 
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
services:
  - name: docker:20-dind
    alias: docker
    command: ["--tls=false", "--mtu=1450"]
before_script:
  - docker info

stages:
  - test
  - build

test_:
  stage: test
  script:
    - make test

build:
  stage: build
  script:
    - make build

# release:
#   stage: release
#   only:
#     - master
#   script:
#     - make release
